import { Profile, Service, Project, Achievement, Testimonial, Faq, SiteSettings } from '../types';

export const defaultProfile: Profile = {
  name: 'Samson Eke',
  highlightedName: 'SamTeck Digital',
  title: 'Full-Stack Software Engineer & Solutions Architect',
  eyebrow: 'SOFTWARE DEVELOPER',
  heroHeadline: "Hi, I'm",
  heroDescription: 'I build scalable, high-performance digital products and cloud-native applications that solve real-world problems and create measurable impact.',
  bio: "I'm a passionate software developer and solutions architect with a strong foundation in full-stack web and cloud systems. I love turning ideas into clean, efficient, and scalable digital solutions. My focus is on building products that deliver real value and exceptional user experiences.",
  email: 'hello@samteckdigital.com',
  phone: '+234 812 345 6789',
  location: 'Lagos, Nigeria & Remote',
  openToWork: true,
  profileImageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800', // high-res tech professional portrait matching CEO
  aboutImageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1000', // high-tech developer workstation
  cvUrl: '#',
  yearsExperience: '5+',
  projectsCompleted: '35+',
  happyClients: '20+',
  valueIndicators: [
    { id: '1', label: 'Clean Code', icon: 'Code' },
    { id: '2', label: 'Scalable Solutions', icon: 'Cpu' },
    { id: '3', label: 'User Focused', icon: 'Users' },
    { id: '4', label: 'Performance Driven', icon: 'Zap' },
  ],
  technologies: [
    { name: 'React', iconName: 'Atom', category: 'Frontend' },
    { name: 'Next.js', iconName: 'Layers', category: 'Fullstack' },
    { name: 'TypeScript', iconName: 'FileCode', category: 'Language' },
    { name: 'Node.js', iconName: 'Server', category: 'Backend' },
    { name: 'Python', iconName: 'Terminal', category: 'Backend' },
    { name: 'PostgreSQL', iconName: 'Database', category: 'Database' },
    { name: 'Tailwind CSS', iconName: 'Palette', category: 'Styling' },
    { name: 'Firebase', iconName: 'Flame', category: 'Cloud' },
  ]
};

export const defaultServices: Service[] = [
  {
    id: 'srv-1',
    title: 'Web Development',
    description: 'Building fast, responsive, modern, and accessible web applications tailored to business goals.',
    iconName: 'CodeXml',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'srv-2',
    title: 'Backend Development',
    description: 'Designing robust REST & GraphQL APIs, microservices, and secure server-side infrastructures.',
    iconName: 'Smartphone',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'srv-3',
    title: 'Database Design',
    description: 'Creating efficient, secure, and optimized relational and NoSQL database schemas for heavy scale.',
    iconName: 'Database',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'srv-4',
    title: 'Cloud & DevOps',
    description: 'Deploying and managing cloud workloads on modern platforms with automated CI/CD pipelines.',
    iconName: 'Cloud',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'srv-5',
    title: 'UI/UX Implementation',
    description: 'Bringing complex designs to life with pixel-perfect precision, micro-interactions, and accessible UIs.',
    iconName: 'Layout',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'srv-6',
    title: 'Performance Optimization',
    description: 'Improving speed, SEO metrics, database queries, and overall application performance benchmarks.',
    iconName: 'Rocket',
    displayOrder: 6,
    isActive: true,
  },
];

export const defaultProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'TaskFlow SaaS',
    slug: 'taskflow-saas',
    shortDescription: 'A complete project management SaaS with real-time tasks, team workspaces, analytics, and file sharing.',
    longDescription: 'TaskFlow is an enterprise-ready collaborative workflow platform engineered to streamline sprint planning, task delegation, and velocity tracking. Built with high concurrency handling and instant state synchronization.',
    projectImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=800',
    category: 'SaaS',
    technologies: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS'],
    liveUrl: 'https://example.com/taskflow',
    githubUrl: 'https://github.com/samteckdigital/taskflow-saas',
    isFeatured: true,
    displayOrder: 1,
    problem: 'Disjointed team communication and complex project tracking causing bottlenecks in fast-moving engineering teams.',
    solution: 'Engineered a unified workspace featuring visual Kanban boards, automated burn-down charts, and instant notifications.',
    features: ['Real-time team collaboration', 'Automated sprint reports', 'Role-based access control', 'Encrypted attachments'],
    role: 'Lead Architect & Full-Stack Developer',
    results: 'Enabled 40+ engineering teams to decrease sprint cycle times by 28% and improve visibility across cross-functional tasks.'
  },
  {
    id: 'proj-2',
    name: 'ShopEase E-Commerce',
    slug: 'shopease-ecommerce',
    shortDescription: 'A modern headless e-commerce store with cart, multi-currency checkout, and payment gateway integration.',
    longDescription: 'ShopEase delivers lightning-fast product filtering, instant inventory synchronization, and secure multi-currency payment processing integrated with Stripe and local payment channels.',
    projectImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    category: 'Full Stack',
    technologies: ['React', 'Node.js', 'Express', 'Stripe', 'Tailwind CSS'],
    liveUrl: 'https://example.com/shopease',
    githubUrl: 'https://github.com/samteckdigital/shopease-commerce',
    isFeatured: true,
    displayOrder: 2,
    problem: 'Slow page load times on legacy Shopify theme resulting in high cart abandonment and lost conversions.',
    solution: 'Rebuilt as a headless architecture with sub-second page loads, edge caching, and optimized checkout flow.',
    features: ['Sub-second catalog search', 'Multi-currency conversion', 'One-click checkout', 'Admin order dashboard'],
    role: 'Full-Stack Developer',
    results: 'Increased checkout conversion rate by 34% with zero checkout downtime during peak seasonal traffic.'
  },
  {
    id: 'proj-3',
    name: 'FinTrack Dashboard',
    slug: 'fintrack-dashboard',
    shortDescription: 'Personal finance and corporate budgeting dashboard for tracking income, expenses, and portfolio health.',
    longDescription: 'FinTrack provides real-time financial telemetry with interactive visual charts, automated expense categorization, multi-bank syncing, and predictive cashflow forecasts.',
    projectImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    category: 'Web App',
    technologies: ['TypeScript', 'React', 'D3.js', 'PostgreSQL', 'Tailwind CSS'],
    liveUrl: 'https://example.com/fintrack',
    githubUrl: 'https://github.com/samteckdigital/fintrack-dashboard',
    isFeatured: true,
    displayOrder: 3,
    problem: 'SMEs and professionals struggle with tracking diverse income streams and complex recurring expenses.',
    solution: 'Designed an interactive analytics suite with automated ledger tagging and intelligent budgeting alerts.',
    features: ['Interactive D3 charts', 'AI-assisted expense tagging', 'PDF/CSV exports', 'Bank integration webhooks'],
    role: 'Frontend & Data Visualization Lead',
    results: 'Processed over $2.5M in monthly transaction telemetry for 12,000+ active platform users.'
  },
  {
    id: 'proj-4',
    name: 'DevPortfolio Platform',
    slug: 'devportfolio-platform',
    shortDescription: 'A dynamic, high-performance portfolio CMS platform for modern software developers and digital agencies.',
    longDescription: 'A customizable, serverless developer portfolio with a dedicated admin management console, real-time database synchronization, contact routing, and full SEO metadata engine.',
    projectImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800',
    category: 'Full Stack',
    technologies: ['React', 'TypeScript', 'Firebase', 'Tailwind CSS', 'Framer Motion'],
    liveUrl: 'https://example.com/devportfolio',
    githubUrl: 'https://github.com/samteckdigital/devportfolio-template',
    isFeatured: true,
    displayOrder: 4,
    problem: 'Developers waste weeks re-coding portfolios from scratch whenever they need to update projects or credentials.',
    solution: 'Created an autonomous CMS-backed portfolio with live editing, dark mode design system, and verified API channels.',
    features: ['Instant content CMS', 'Responsive dark navy theme', 'Interactive timeline', 'Contact message inbox'],
    role: 'Lead Designer & Engineer',
    results: 'Ranked top 1% on Google Lighthouse for performance, SEO, accessibility, and best practices.'
  }
];

export const defaultAchievements: Achievement[] = [
  {
    id: 'ach-1',
    year: '2021',
    title: 'B.Sc. in Computer Science',
    description: 'Graduated with academic distinction in Systems Architecture & Algorithms.',
    iconName: 'GraduationCap',
    displayOrder: 1,
  },
  {
    id: 'ach-2',
    year: '2022',
    title: 'Started Developer Journey',
    description: 'Began building production web projects and contracting for international startups.',
    iconName: 'Code',
    displayOrder: 2,
  },
  {
    id: 'ach-3',
    year: '2023',
    title: 'Full-Time Engineer',
    description: 'Joined a high-growth tech company as Senior Frontend & Systems Developer.',
    iconName: 'Briefcase',
    displayOrder: 3,
  },
  {
    id: 'ach-4',
    year: '2024',
    title: 'Top Performer Award',
    description: 'Recognized for delivering high-impact cloud migrations and scalable client architectures.',
    iconName: 'Trophy',
    displayOrder: 4,
  },
  {
    id: 'ach-5',
    year: '2025 - Present',
    title: 'Founder, SamTeck Digital',
    description: 'Empowering global clients and building next-generation SaaS digital platforms.',
    iconName: 'Rocket',
    displayOrder: 5,
  },
];

export const defaultTestimonials: Testimonial[] = [
  {
    id: 'test-1',
    clientName: 'David Adebayo',
    clientRole: 'CTO & Co-Founder',
    company: 'TechWave Global',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    testimonialText: 'SamTeck Digital is an exceptional engineering partner. They understood our complex requirements perfectly and delivered a high-quality product on time. Communication, architecture, and code quality were outstanding.',
    rating: 5,
    isFeatured: true,
    displayOrder: 1,
  },
  {
    id: 'test-2',
    clientName: 'Sarah Jenkins',
    clientRole: 'Head of Product',
    company: 'Nexus SaaS Solutions',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    testimonialText: 'Working with Samson was a game-changer for our dashboard launch. The attention to detail, responsiveness, and performance optimization blew our leadership team away.',
    rating: 5,
    isFeatured: true,
    displayOrder: 2,
  },
  {
    id: 'test-3',
    clientName: 'Michael Chen',
    clientRole: 'Managing Director',
    company: 'Apex Digital Ventures',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    testimonialText: 'Flawless execution from initial wireframes to production cloud deployment. Highly recommend SamTeck Digital for any serious software engineering endeavor.',
    rating: 5,
    isFeatured: true,
    displayOrder: 3,
  },
];

export const defaultFaqs: Faq[] = [
  {
    id: 'faq-1',
    question: 'What technologies and frameworks do you work with?',
    answer: 'I specialize in full-stack JavaScript/TypeScript ecosystems including React, Next.js, Node.js, Express, Python, PostgreSQL, Firebase, Tailwind CSS, Docker, and AWS cloud infrastructures.',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'faq-2',
    question: 'Are you available for freelance projects or full-time roles?',
    answer: 'Yes! I am actively available for select high-impact contract projects, technical consulting, and dedicated engineering roles worldwide.',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'faq-3',
    question: 'How do you ensure projects are delivered on time and within budget?',
    answer: 'I follow agile development cycles with clear milestone breakdowns, weekly sprint reviews, continuous staging previews, and transparent asynchronous updates.',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'faq-4',
    question: 'Do you provide post-launch support and maintenance?',
    answer: 'Absolutely. All project engagements include a warranty period along with flexible ongoing maintenance plans for updates, monitoring, and scaling.',
    displayOrder: 4,
    isActive: true,
  },
];

export const defaultSiteSettings: SiteSettings = {
  brandName: 'SamTeck Digital',
  brandTagline: 'Building digital solutions that drive impact.',
  siteTitle: 'SamTeck Digital | Software Developer & Full-Stack Engineer',
  metaDescription: 'Portfolio of SamTeck Digital - Full-stack developer building scalable, high-performance web applications and digital products.',
  copyrightText: '2026 SamTeck Digital. All rights reserved.',
  socialLinks: [
    { id: '1', platform: 'GitHub', url: 'https://github.com', iconName: 'Github', displayOrder: 1 },
    { id: '2', platform: 'LinkedIn', url: 'https://linkedin.com', iconName: 'Linkedin', displayOrder: 2 },
    { id: '3', platform: 'Twitter', url: 'https://twitter.com', iconName: 'Twitter', displayOrder: 3 },
    { id: '4', platform: 'Email', url: 'mailto:hello@samteckdigital.com', iconName: 'Mail', displayOrder: 4 },
  ]
};
